# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Selenium on github action

on:
  schedule:
  # 定时运行 UTC 21:00(北京时间 13:00)
  - cron: '0 21 * * *'
  workflow_dispatch: 
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      #- name: Remove default Chromium
      #  run: sudo apt purge chromium-browser
      #- name: Install a new Chromium
      #  run: sudo apt install -y chromium-browser
      - name: Install all needs packages
        run: pip install chromedriver-autoinstaller webdriver-manager selenium
      - name: Run the script
        run: python main.py
      
    
